def make( option )
	Makefiles.file_paths.each{|file_path|
		sh "make #{option} -f #{file_path}"
	}
end

tasks = {
	:debug 		=> Proc.new,
	:release	=> Proc.new,
	:clean		=> Proc.new{ make( "clean" ) }
}

desc "Debug Build"
task :debug do
	tasks[ :debug ]
end

desc "Release Build"
task :release do
	tasks[ :release ]
end

desc "Clean Build"
task :clean do
	tasks[ :clean ]
end

desc "Remove Makefiles"
task :rm do
	Makefiles.file_paths.each{|file_path|
		sh "rm -f #{file_path}"
	}
end

desc "Output Makefiles"
task :output do
	Makefiles.each{|makefile|
		makefile.output
	}
end
