require "./Makefiles"

def make( option )
	Makefiles.file_paths.each{|file_path|
		sh "make #{option} -f #{file_path}"
	}
end

task :default => [ :output ]

desc "Debug Build"
task :debug do
	compile_options = "-g"
	make "COMPILE_OPTIONS='#{compile_options}'"
end

desc "Release Build"
task :release do
	compile_options = "-O2"
	make "COMPILE_OPTIONS='#{compile_options}'"
end

desc "Clean Build"
task :clean do
	make "clean"
end

desc "Remove Makefiles"
task :rm do
	Makefiles.file_paths.each{|file_path|
		sh "rm -f #{file_path}"
	}
end

desc "Output Makefiles"
task :output do
	Makefiles.each{|makefile|
		makefile.output
	}
end
